package ir.ut.ce.awtr.tts;

import java.util.Objects;

/** Rules for state identifiers supplied by an input model. */
public final class StateIdentifiers {

    /** Separates the components of state identifiers created by transformations. */
    public static final char GENERATED_STATE_SEPARATOR = '#';

    private StateIdentifiers() {
    }

    /**
     * Validates an input state identifier.
     *
     * @return {@code stateId}, for convenient use at assignment sites
     * @throws InvalidModelException if the identifier uses the separator reserved
     *                               for generated states
     */
    public static String requireValid(String stateId) {
        Objects.requireNonNull(stateId, "stateId");
        if (stateId.indexOf(GENERATED_STATE_SEPARATOR) >= 0) {
            throw new InvalidModelException("invalid state id '" + stateId + "': '"
                    + GENERATED_STATE_SEPARATOR
                    + "' is reserved for states generated by internal transformations");
        }
        return stateId;
    }
}
